name: "Get & cache dependencies"
description: "Get the dependencies (via npm) and cache them"
inputs:
  caching:
    description: "Weather to cache dependencies or not"
    required: false
    default: "true"
outputs:
  used-cache:
    description: "Whether the cache was used"
    value: ${{ steps.test-output.outputs.cache }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
      shell: bash
    - name: Output value caching
      id: test-output
      run: |
        echo "cache=${{inputs.caching}}" >> $GITHUB_OUTPUT
      shell: bash
    # - name: Check Info Output
    #   run: |
    #     echo ${{ toJSON(steps.test-output.outputs) }}
    #   shell: bash
