name: Practice make perfect
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        id: cache-deps
        with:
          caching: "true"
      - name: Build app
        run: |
          npm run build
      - name: Output info
        run: |
          echo "Used cache? ${{ toJSON(steps.cache-deps) }}"

  informaion:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Output script from JS Script
        uses: "./.github/actions/js-script"
