name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Put some description here
        default: dist
        type: string

jobs:
  deploy:
    outputs:
      outcome: TEST
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Info
        run: echo "Deploying & Uploading..."
